version: "3"

volumes:
    static-files:
        driver: local
    postgres:
        driver: local

services:
    db:
        image: postgres:14.2
        volumes:
            - postgres:/var/lib/postgresql/data/pgdata
        env_file:
            - ./config/environment/.env

    webserver:
        image: nginx:1.15
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webapp
        volumes:
            - static-files:/srv/static-files
            # - ./config/nginx/conf.d:/etc/nginx/conf.d
            # - ./config/webserver/nginx.tmpl:/etc/nginx/conf.d/nginx.tmpl
        env_file:
            - ./config/environment/.env
        networks:
            - nginx_network

    webapp:
        build:
            context: webapp
        volumes:
            - ./webapp/chaesmos:/srv/chaesmos
            - static-files:/srv/static-files
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - ./config/environment/.env
        networks:
            - nginx_network

networks:
    nginx_network:
        driver: bridge
