# Generated by Django 4.0.5 on 2022-07-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='seleted_date',
            new_name='selected_date',
        ),
    ]
