# Generated by Django 4.0.5 on 2022-07-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_usersession_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('main', models.TextField()),
                ('seleted_date', models.DateField()),
                ('fk_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='users.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('fk_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='postoffice.letter')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main', models.TextField()),
                ('fk_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='postoffice.letter')),
                ('fk_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='users.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
