# Generated by Django 4.0.5 on 2022-08-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersession_expired_at'),
        ('postoffice', '0003_alter_letter_fk_writer_alter_solution_fk_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='fk_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='users.useraccount'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='fk_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='postoffice.letter'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='fk_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to='users.useraccount'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='fk_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='postoffice.letter'),
        ),
        migrations.CreateModel(
            name='DailyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_at', models.DateTimeField()),
                ('fk_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.letter')),
                ('fk_reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyposts', to='users.useraccount')),
            ],
        ),
    ]
