# Generated by Django 4.0.5 on 2022-08-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0004_alter_letter_fk_writer_alter_solution_fk_letter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-id']},
        ),
    ]
